language: python
cache: pip

python:
  - "2.7"
  - "3.6"

sudo: false

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1

matrix:
  exclude:
    - { python: 2.7, env: DJANGO=2.0 }
    - { python: 2.7, env: DJANGO=2.1 }

  fast_finish: true

install:
  - pip install tox-travis coverage coveralls

script:
  - coverage erase
  - tox

after_success:
  - coverage combine
  - coveralls
