language: python

python:
  - "2.7"
  - "3.6"

sudo: false

env:
    - TOX_ENV=py27-django1.11
    - TOX_ENV=py36-django1.11
    - TOX_ENV=py36-django2.0
    - TOX_ENV=py36-django2.1

matrix:
  fast_finish: true

install:
  - pip install tox-travis coverage coveralls

script:
  - coverage erase
  - tox

after_success:
  - coverage combine
  - coveralls
